<?php

namespace app\index\controller;


/**
 *
 */
class Demo extends Base {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function index(){
        return false;
        $plugin_path = ROOT_PATH . '/public/content/plugin/jiuwu_balance';
        if(file_exists($plugin_path . '/director')){

            copydirs($plugin_path . '/director', ROOT_PATH);
            echo '存在';
        }else{
            echo '不存在';
        }
    }

}
