<?php

namespace app\shop\controller;

use think\Db;
use think\Session;

class Login extends Base {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session::has('uid')){
            header('location: ' . url('/'));
            die;
        }
    }

    public function index() {
        if($this->site['login'] == 0){
            $this->error('网站登录功能已关闭！');
        }
        if($this->request->isAjax()){
            $post = $this->request->param();
            $account_type = getAccountType($post['account']);
            $user = db::name('user')->where([$account_type => $post['account']])->find();
            if(!$user){
                $this->error('帐号不存在');
            }

            $password = $this->getEncryptPassword($post['password'], $user['salt']);
            if($password != $user['password']){
                $this->error('密码错误');
            }
            session::set('uid', $user['id']);
            session::set("tourist", null);
            $this->success('登录成功');
        }
        return view($this->template_path . 'login.html');
    }

}
