<?php

namespace app\shop\controller;

use fast\Random;
use think\Db;
use think\Session;

class Register extends Base {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session::has('uid')){
            header('location: ' . url('user/index'));
            die;
        }
    }

    public function index() {
        if($this->site['register'] == 0){
            $this->error('网站注册功能已关闭！');
        }
        if($this->request->isAjax()){
            $post = $this->request->param();
            Db::startTrans();
            try {
                $where = [
                    'mobile' => $post['tel'],
                ];
                $user = db::name('user')->where($where)->find();
                if($user){
                    throw new \Exception("手机号被占用，请更换其他手机号");
                }
                $insert = [
                    "mobile" => $post['tel'],
                    "salt" => Random::alnum(),
                    "nickname" => $post['tel'],
                    "createtime" => time(),
                ];
                $insert["password"] = $this->getEncryptPassword($post['password'], $insert['salt']);
                $uid = db::name("user")->insertGetId($insert);
                db::name("options")->where(["option_name" => "user_total"])->setInc("option_content");
                Db::commit();
            }catch (\Exception $e){
                Db::rollback();
                $this->error($e->getMessage());
            }
            if($uid){
                session::set("uid", $uid);
                session::set("tourist", null);
                $this->success("注册成功");
            }else{
                $this->error("注册失败");
            }
        }
        return view($this->template_path . "register.html");
    }

}
